package Ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.math.BigInteger; 
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException;
import com.google.gson.*;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */

public class basic extends javax.swing.JFrame {



    /**
     * Creates new form basic
     */

    public basic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sideplane = new javax.swing.JPanel();
        side_plane_btn2_con = new javax.swing.JPanel();
        home_icon1 = new javax.swing.JLabel();
        Side_plane_btn_2 = new javax.swing.JLabel();
        side_plane_btn3_con = new javax.swing.JPanel();
        home_icon2 = new javax.swing.JLabel();
        Side_plane_btn_3 = new javax.swing.JLabel();
        side_plane_btn4_con = new javax.swing.JPanel();
        home_icon3 = new javax.swing.JLabel();
        Side_plane_btn_4 = new javax.swing.JLabel();
        side_plane_btn5_con = new javax.swing.JPanel();
        home_icon4 = new javax.swing.JLabel();
        Side_plane_btn_5 = new javax.swing.JLabel();
        side_plane_btn1_con = new javax.swing.JPanel();
        home_icon = new javax.swing.JLabel();
        Side_Plane_btn_1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sidePlane_JAVA_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Sideplane1 = new javax.swing.JPanel();
        side_plane_btn2_con1 = new javax.swing.JPanel();
        Side_plane_btn_6 = new javax.swing.JLabel();
        side_plane_btn5_con1 = new javax.swing.JPanel();
        Side_plane_btn_9 = new javax.swing.JLabel();
        home_icon8 = new javax.swing.JLabel();
        side_plane_btn1_con1 = new javax.swing.JPanel();
        Side_Plane_btn_2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        sidePlane_JAVA_label1 = new javax.swing.JLabel();
        home_icon10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        dashboard_close_btn2 = new javax.swing.JLabel();
        bsk_gd2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dashboard_close_btn1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        Sideplane.setBackground(new java.awt.Color(54, 33, 89));
        Sideplane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_plane_btn2_con.setBackground(new java.awt.Color(69, 43, 100));
        side_plane_btn2_con.setLayout(null);

        home_icon1.setForeground(new java.awt.Color(255, 255, 255));
        home_icon1.setText("HOME Icon");
        side_plane_btn2_con.add(home_icon1);
        home_icon1.setBounds(23, 13, 33, 24);

        Side_plane_btn_2.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        Side_plane_btn_2.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_2.setText("Employ Benefits");
        Side_plane_btn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_plane_btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_plane_btn_2MousePressed(evt);
            }
        });
        side_plane_btn2_con.add(Side_plane_btn_2);
        Side_plane_btn_2.setBounds(91, 17, 179, 18);

        Sideplane.add(side_plane_btn2_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 50));

        side_plane_btn3_con.setBackground(new java.awt.Color(85, 45, 100));
        side_plane_btn3_con.setLayout(null);

        home_icon2.setForeground(new java.awt.Color(255, 255, 255));
        home_icon2.setText("HOME Icon");
        side_plane_btn3_con.add(home_icon2);
        home_icon2.setBounds(23, 13, 33, 24);

        Side_plane_btn_3.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        Side_plane_btn_3.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_3.setText("Employ Benefits");
        Side_plane_btn_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_plane_btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_plane_btn_3MousePressed(evt);
            }
        });
        side_plane_btn3_con.add(Side_plane_btn_3);
        Side_plane_btn_3.setBounds(91, 17, 179, 20);

        Sideplane.add(side_plane_btn3_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 50));

        side_plane_btn4_con.setBackground(new java.awt.Color(79, 45, 119));
        side_plane_btn4_con.setLayout(null);

        home_icon3.setForeground(new java.awt.Color(255, 255, 255));
        home_icon3.setText("HOME Icon");
        side_plane_btn4_con.add(home_icon3);
        home_icon3.setBounds(23, 13, 33, 24);

        Side_plane_btn_4.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        Side_plane_btn_4.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_4.setText("Employ Benefits");
        Side_plane_btn_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_plane_btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_plane_btn_4MousePressed(evt);
            }
        });
        side_plane_btn4_con.add(Side_plane_btn_4);
        Side_plane_btn_4.setBounds(91, 17, 179, 18);

        Sideplane.add(side_plane_btn4_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 50));

        side_plane_btn5_con.setBackground(new java.awt.Color(69, 55, 90));
        side_plane_btn5_con.setLayout(null);

        home_icon4.setForeground(new java.awt.Color(255, 255, 255));
        home_icon4.setText("HOME Icon");
        side_plane_btn5_con.add(home_icon4);
        home_icon4.setBounds(23, 13, 33, 24);

        Side_plane_btn_5.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        Side_plane_btn_5.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_5.setText("Employ Benefits");
        Side_plane_btn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        side_plane_btn5_con.add(Side_plane_btn_5);
        Side_plane_btn_5.setBounds(91, 17, 179, 18);

        Sideplane.add(side_plane_btn5_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 300, 50));

        side_plane_btn1_con.setBackground(new java.awt.Color(85, 65, 118));
        side_plane_btn1_con.setLayout(null);

        home_icon.setForeground(new java.awt.Color(255, 255, 255));
        home_icon.setText("HOME Icon");
        side_plane_btn1_con.add(home_icon);
        home_icon.setBounds(23, 13, 33, 24);

        Side_Plane_btn_1.setBackground(new java.awt.Color(255, 255, 255));
        Side_Plane_btn_1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 13)); // NOI18N
        Side_Plane_btn_1.setForeground(new java.awt.Color(255, 255, 255));
        Side_Plane_btn_1.setText("Employ Benefits");
        Side_Plane_btn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_Plane_btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_Plane_btn_1MousePressed(evt);
            }
        });
        side_plane_btn1_con.add(Side_Plane_btn_1);
        Side_Plane_btn_1.setBounds(91, 17, 179, 18);

        Sideplane.add(side_plane_btn1_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 50));
        Sideplane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 130, 20));

        sidePlane_JAVA_label.setBackground(new java.awt.Color(255, 255, 255));
        sidePlane_JAVA_label.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        sidePlane_JAVA_label.setForeground(new java.awt.Color(255, 255, 255));
        sidePlane_JAVA_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidePlane_JAVA_label.setText("JAVA UI");
        sidePlane_JAVA_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidePlane_JAVA_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePlane_JAVA_labelMousePressed(evt);
            }
        });
        Sideplane.add(sidePlane_JAVA_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jframe_home");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sideplane1.setBackground(new java.awt.Color(54, 33, 89));
        Sideplane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_plane_btn2_con1.setBackground(new java.awt.Color(69, 43, 100));
        side_plane_btn2_con1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                side_plane_btn2_con1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                side_plane_btn2_con1MousePressed(evt);
            }
        });
        side_plane_btn2_con1.setLayout(null);

        Side_plane_btn_6.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Side_plane_btn_6.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_6.setText(" Download Certificate");
        Side_plane_btn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_plane_btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_plane_btn_6MousePressed(evt);
            }
        });
        side_plane_btn2_con1.add(Side_plane_btn_6);
        Side_plane_btn_6.setBounds(20, 20, 179, 18);

        Sideplane1.add(side_plane_btn2_con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 50));

        side_plane_btn5_con1.setBackground(new java.awt.Color(69, 55, 90));
        side_plane_btn5_con1.setLayout(null);

        Side_plane_btn_9.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Side_plane_btn_9.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_9.setText("ABOUT ");
        Side_plane_btn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_plane_btn_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_plane_btn_9MousePressed(evt);
            }
        });
        side_plane_btn5_con1.add(Side_plane_btn_9);
        Side_plane_btn_9.setBounds(30, 10, 179, 25);

        home_icon8.setForeground(new java.awt.Color(255, 255, 255));
        side_plane_btn5_con1.add(home_icon8);
        home_icon8.setBounds(20, 0, 0, 50);

        Sideplane1.add(side_plane_btn5_con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 50));

        side_plane_btn1_con1.setBackground(new java.awt.Color(85, 65, 118));
        side_plane_btn1_con1.setLayout(null);

        Side_Plane_btn_2.setBackground(new java.awt.Color(255, 255, 255));
        Side_Plane_btn_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Side_Plane_btn_2.setForeground(new java.awt.Color(255, 255, 255));
        Side_Plane_btn_2.setText("Vaccine Tracker");
        Side_Plane_btn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_Plane_btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_Plane_btn_2MousePressed(evt);
            }
        });
        side_plane_btn1_con1.add(Side_Plane_btn_2);
        Side_Plane_btn_2.setBounds(30, 20, 179, 18);

        Sideplane1.add(side_plane_btn1_con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 50));
        Sideplane1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, 20));

        sidePlane_JAVA_label1.setBackground(new java.awt.Color(255, 255, 255));
        sidePlane_JAVA_label1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        sidePlane_JAVA_label1.setForeground(new java.awt.Color(255, 255, 255));
        sidePlane_JAVA_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidePlane_JAVA_label1.setText("Covid-19");
        sidePlane_JAVA_label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidePlane_JAVA_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePlane_JAVA_label1MousePressed(evt);
            }
        });
        Sideplane1.add(sidePlane_JAVA_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, 30));

        home_icon10.setForeground(new java.awt.Color(255, 255, 255));
        Sideplane1.add(home_icon10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 110));

        jPanel2.add(Sideplane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 680));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        dashboard_close_btn2.setBackground(new java.awt.Color(255, 255, 255));
        dashboard_close_btn2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        dashboard_close_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_close_btn2.setText("X");
        dashboard_close_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboard_close_btn2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(dashboard_close_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(dashboard_close_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        bsk_gd2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 0, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel6);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vaccine Tracker");
        jPanel3.add(jLabel7);

        dashboard_close_btn1.setBackground(new java.awt.Color(255, 255, 255));
        dashboard_close_btn1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        dashboard_close_btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_close_btn1.setText("X");
        dashboard_close_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboard_close_btn1MousePressed(evt);
            }
        });

        jLabel1.setText("Enter Pincode :  ");

        jLabel2.setText("Enter Date      :");

        jTextField2.setToolTipText("dd-mm-yyyy");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout bsk_gd2Layout = new javax.swing.GroupLayout(bsk_gd2);
        bsk_gd2.setLayout(bsk_gd2Layout);
        bsk_gd2Layout.setHorizontalGroup(
            bsk_gd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bsk_gd2Layout.createSequentialGroup()
                .addGroup(bsk_gd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bsk_gd2Layout.createSequentialGroup()
                        .addGap(710, 710, 710)
                        .addComponent(dashboard_close_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bsk_gd2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bsk_gd2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bsk_gd2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
        );
        bsk_gd2Layout.setVerticalGroup(
            bsk_gd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bsk_gd2Layout.createSequentialGroup()
                .addComponent(dashboard_close_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(bsk_gd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(bsk_gd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel2.add(bsk_gd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 830, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1045, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Side_plane_btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_plane_btn_2MousePressed
    }//GEN-LAST:event_Side_plane_btn_2MousePressed

    private void Side_plane_btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_plane_btn_3MousePressed

    }//GEN-LAST:event_Side_plane_btn_3MousePressed

    private void Side_plane_btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_plane_btn_4MousePressed
        bsk_gd2.setVisible(false);
    }//GEN-LAST:event_Side_plane_btn_4MousePressed

    private void Side_Plane_btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_Plane_btn_1MousePressed
    }//GEN-LAST:event_Side_Plane_btn_1MousePressed

    private void sidePlane_JAVA_labelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePlane_JAVA_labelMousePressed
        bsk_gd2.setVisible(false);        // TODO add your handling code here:

    }//GEN-LAST:event_sidePlane_JAVA_labelMousePressed

    private void dashboard_close_btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_close_btn1MousePressed
        System.exit(0);
    }//GEN-LAST:event_dashboard_close_btn1MousePressed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    void run2(long pincode,String date) throws UnirestException, ParseException, IOException{

        String host = "https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByPin?pincode=" + pincode + "&date=" + date;
        System.out.println(host);
        HttpResponse<JsonNode> response;
                    response = Unirest.get(host)
                            .asJson();
        jTextArea1.selectAll();
        jTextArea1.replaceSelection("");

        System.out.println(response.getStatus());
        System.out.println(response.getBody());
        //below part is to show the json file in readable format
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        JsonParser jp = new JsonParser();
        JsonElement je = jp.parse(response.getBody().toString());
        String prettyJsonString = gson.toJson(je);
        System.out.println(prettyJsonString);
        String readLine;
        BufferedReader in = new BufferedReader(
                new InputStreamReader(response.getRawBody()));
        StringBuilder responses = new StringBuilder();
        while ((readLine = in.readLine()) != null) {
            responses.append(readLine);
        }//print result
        JSONParser parser = new JSONParser();
        JSONObject json = (JSONObject) parser.parse(responses.toString());
        JSONArray responseArr = (JSONArray) json.get("sessions");
        for (Object object: responseArr){
            JSONObject jsonObj = (JSONObject) object;
            Long pincodel = (Long) jsonObj.get("pincode");
            String name = (String) jsonObj.get("name");
            String vaccine = (String) jsonObj.get("vaccine");
            String address = jsonObj.get("address") + ", " + jsonObj.get("district_name") + ", " +
                    jsonObj.get("state_name") + " " + pincodel;
            String fee_type = (String) jsonObj.get("fee_type");
            Long min_age = (Long) jsonObj.get("min_age_limit");

            System.out.println(name);
            System.out.println(address);
            System.out.println(fee_type);

            
            Long capacity_dose1 = (Long) jsonObj.get("available_capacity_dose1");
            Long capacity_dose2 = (Long) jsonObj.get("available_capacity_dose2");

            
            jTextArea1.append("Name:\t\t" + name + "\n");
            jTextArea1.append("Vaccine:\t\t" + vaccine + "\n");
            jTextArea1.append("Centre Location:\t" + address + "\n");
            jTextArea1.append("Fee Type:\t\t" + fee_type + "\n");
            jTextArea1.append("Minimum Age:\t\t" + Long.toString(min_age) + "\n");
            jTextArea1.append("Dose 1 Capacity:\t" + Long.toString(capacity_dose1) + "\n");
            jTextArea1.append("Dose 2 Capacity:\t" + Long.toString(capacity_dose2) + "\n");
            jTextArea1.append("\n\n");
        }       
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        long pincode = Integer.parseInt(jTextField1.getText());
        String date = jTextField2.getText();
                Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                try {
                    run2(pincode,date);
                } catch (UnirestException ex) {
                    Logger.getLogger(basic.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(basic.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(basic.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }, 0, 5000);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Side_plane_btn_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_plane_btn_6MousePressed
        new NewJFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Side_plane_btn_6MousePressed

    private void Side_plane_btn_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_plane_btn_9MousePressed
        jPanel1.setVisible(true);
    }//GEN-LAST:event_Side_plane_btn_9MousePressed

    private void Side_Plane_btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_Plane_btn_2MousePressed

    }//GEN-LAST:event_Side_Plane_btn_2MousePressed

    private void sidePlane_JAVA_label1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePlane_JAVA_label1MousePressed
        bsk_gd2.setVisible(false);        // TODO add your handling code here:
        jPanel1.setVisible(false);
    }//GEN-LAST:event_sidePlane_JAVA_label1MousePressed

    private void dashboard_close_btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_close_btn2MousePressed
        System.exit(0);
    }//GEN-LAST:event_dashboard_close_btn2MousePressed

    private void side_plane_btn2_con1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_side_plane_btn2_con1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_side_plane_btn2_con1MouseClicked

    private void side_plane_btn2_con1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_side_plane_btn2_con1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_side_plane_btn2_con1MousePressed

    
    /**
     * @param args the command line arguments
     */
     public static byte[] getSHA(String input) throws NoSuchAlgorithmException
    { 
        // Static getInstance method is called with hashing SHA 
        MessageDigest md = MessageDigest.getInstance("SHA-256"); 
  
        // digest() method called 
        // to calculate message digest of an input 
        // and return array of byte
        return md.digest(input.getBytes(StandardCharsets.UTF_8)); 
    }
     public static String toHexString(byte[] hash)
    {
        // Convert byte array into signum representation 
        BigInteger number = new BigInteger(1, hash); 
  
        // Convert message digest into hex value 
        StringBuilder hexString = new StringBuilder(number.toString(16)); 
  
        // Pad with leading zeros
        while (hexString.length() < 32) 
        { 
            hexString.insert(0, '0'); 
        } 
  
        return hexString.toString(); 
    }
    
    public static void main(String args[]) throws UnirestException, NoSuchAlgorithmException, ParseException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basic().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Side_Plane_btn_1;
    private javax.swing.JLabel Side_Plane_btn_2;
    private javax.swing.JLabel Side_plane_btn_2;
    private javax.swing.JLabel Side_plane_btn_3;
    private javax.swing.JLabel Side_plane_btn_4;
    private javax.swing.JLabel Side_plane_btn_5;
    private javax.swing.JLabel Side_plane_btn_6;
    private javax.swing.JLabel Side_plane_btn_9;
    private javax.swing.JPanel Sideplane;
    private javax.swing.JPanel Sideplane1;
    private javax.swing.JPanel bsk_gd2;
    private javax.swing.JLabel dashboard_close_btn1;
    private javax.swing.JLabel dashboard_close_btn2;
    private javax.swing.JLabel home_icon;
    private javax.swing.JLabel home_icon1;
    private javax.swing.JLabel home_icon10;
    private javax.swing.JLabel home_icon2;
    private javax.swing.JLabel home_icon3;
    private javax.swing.JLabel home_icon4;
    private javax.swing.JLabel home_icon8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel sidePlane_JAVA_label;
    private javax.swing.JLabel sidePlane_JAVA_label1;
    private javax.swing.JPanel side_plane_btn1_con;
    private javax.swing.JPanel side_plane_btn1_con1;
    private javax.swing.JPanel side_plane_btn2_con;
    private javax.swing.JPanel side_plane_btn2_con1;
    private javax.swing.JPanel side_plane_btn3_con;
    private javax.swing.JPanel side_plane_btn4_con;
    private javax.swing.JPanel side_plane_btn5_con;
    private javax.swing.JPanel side_plane_btn5_con1;
    // End of variables declaration//GEN-END:variables
}
