package Ui;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Icon_label = new javax.swing.JLabel();
        Member_login_label = new javax.swing.JLabel();
        Sign_up_label = new javax.swing.JLabel();
        Login_password_label = new javax.swing.JLabel();
        User_name_label = new javax.swing.JLabel();
        Login_Id_label = new javax.swing.JLabel();
        Login_TF = new javax.swing.JTextField();
        User_name_TF = new javax.swing.JTextField();
        password_TF = new javax.swing.JPasswordField();
        Sign_up_button = new javax.swing.JButton();
        Already_mbr_btn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        Icon_label.setForeground(new java.awt.Color(255, 255, 255));
        Icon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ui/icons8-person-64.png"))); // NOI18N

        Member_login_label.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Member_login_label.setForeground(new java.awt.Color(255, 255, 255));
        Member_login_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Member_login_label.setText("MEMBER LOGIN PAGE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Member_login_label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Icon_label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Member_login_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 509);

        Sign_up_label.setFont(new java.awt.Font("Calibri", 0, 35)); // NOI18N
        Sign_up_label.setForeground(new java.awt.Color(102, 102, 102));
        Sign_up_label.setText("Sign Up");
        jPanel1.add(Sign_up_label);
        Sign_up_label.setBounds(430, 40, 180, 70);

        Login_password_label.setForeground(new java.awt.Color(153, 153, 153));
        Login_password_label.setText("Login Password");
        jPanel1.add(Login_password_label);
        Login_password_label.setBounds(380, 190, 110, 16);

        User_name_label.setForeground(new java.awt.Color(153, 153, 153));
        User_name_label.setText("User Name");
        jPanel1.add(User_name_label);
        User_name_label.setBounds(380, 270, 80, 16);

        Login_Id_label.setForeground(new java.awt.Color(153, 153, 153));
        Login_Id_label.setText("Login ID");
        jPanel1.add(Login_Id_label);
        Login_Id_label.setBounds(380, 110, 80, 16);

        Login_TF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Login_TF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.add(Login_TF);
        Login_TF.setBounds(380, 130, 210, 30);

        User_name_TF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        User_name_TF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.add(User_name_TF);
        User_name_TF.setBounds(380, 290, 210, 30);

        password_TF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        password_TF.setAutoscrolls(false);
        password_TF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel1.add(password_TF);
        password_TF.setBounds(380, 210, 210, 30);

        Sign_up_button.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Sign_up_button.setText("Sign Up");
        Sign_up_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 0, true));
        Sign_up_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_up_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Sign_up_button);
        Sign_up_button.setBounds(440, 360, 90, 30);

        Already_mbr_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Already_mbr_btn.setForeground(new java.awt.Color(102, 102, 255));
        Already_mbr_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Already_mbr_btn.setText("Already a Member Login here");
        Already_mbr_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Already_mbr_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Already_mbr_btnMousePressed(evt);
            }
        });
        jPanel1.add(Already_mbr_btn);
        Already_mbr_btn.setBounds(370, 420, 250, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(590, 0, 50, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 634, 470);

        setSize(new java.awt.Dimension(634, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_up_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sign_up_buttonActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
    System.exit(0);
    }//GEN-LAST:event_jLabel2MousePressed

    private void Already_mbr_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Already_mbr_btnMousePressed

        basic frame = new basic();
        frame.setVisible(true);
    }//GEN-LAST:event_Already_mbr_btnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Already_mbr_btn;
    private javax.swing.JLabel Icon_label;
    private javax.swing.JLabel Login_Id_label;
    private javax.swing.JTextField Login_TF;
    private javax.swing.JLabel Login_password_label;
    private javax.swing.JLabel Member_login_label;
    private javax.swing.JButton Sign_up_button;
    private javax.swing.JLabel Sign_up_label;
    private javax.swing.JTextField User_name_TF;
    private javax.swing.JLabel User_name_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password_TF;
    // End of variables declaration//GEN-END:variables
}
