/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;
import static Ui.basic.getSHA;
import static Ui.basic.toHexString;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
/**
 *
 * @author sagar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    public static String txn_id;
    public static String token;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sideplane1 = new javax.swing.JPanel();
        side_plane_btn2_con1 = new javax.swing.JPanel();
        Side_plane_btn_6 = new javax.swing.JLabel();
        side_plane_btn5_con1 = new javax.swing.JPanel();
        Side_plane_btn_9 = new javax.swing.JLabel();
        home_icon8 = new javax.swing.JLabel();
        side_plane_btn1_con1 = new javax.swing.JPanel();
        Side_Plane_btn_2 = new javax.swing.JLabel();
        home_icon9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        sidePlane_JAVA_label1 = new javax.swing.JLabel();
        home_icon10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dashboard_close_btn2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sideplane1.setBackground(new java.awt.Color(54, 33, 89));
        Sideplane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_plane_btn2_con1.setBackground(new java.awt.Color(69, 43, 100));
        side_plane_btn2_con1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                side_plane_btn2_con1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                side_plane_btn2_con1MousePressed(evt);
            }
        });
        side_plane_btn2_con1.setLayout(null);

        Side_plane_btn_6.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Side_plane_btn_6.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_6.setText(" Download Certificate");
        Side_plane_btn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_plane_btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_plane_btn_6MousePressed(evt);
            }
        });
        side_plane_btn2_con1.add(Side_plane_btn_6);
        Side_plane_btn_6.setBounds(10, 17, 260, 22);

        Sideplane1.add(side_plane_btn2_con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 50));

        side_plane_btn5_con1.setBackground(new java.awt.Color(69, 55, 90));
        side_plane_btn5_con1.setLayout(null);

        Side_plane_btn_9.setBackground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Side_plane_btn_9.setForeground(new java.awt.Color(255, 255, 255));
        Side_plane_btn_9.setText("About");
        Side_plane_btn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_plane_btn_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_plane_btn_9MousePressed(evt);
            }
        });
        side_plane_btn5_con1.add(Side_plane_btn_9);
        Side_plane_btn_9.setBounds(20, 17, 250, 22);

        home_icon8.setForeground(new java.awt.Color(255, 255, 255));
        side_plane_btn5_con1.add(home_icon8);
        home_icon8.setBounds(20, 0, 0, 50);

        Sideplane1.add(side_plane_btn5_con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 50));

        side_plane_btn1_con1.setBackground(new java.awt.Color(85, 65, 118));
        side_plane_btn1_con1.setLayout(null);

        Side_Plane_btn_2.setBackground(new java.awt.Color(255, 255, 255));
        Side_Plane_btn_2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        Side_Plane_btn_2.setForeground(new java.awt.Color(255, 255, 255));
        Side_Plane_btn_2.setText("Vaccine Tracker");
        Side_Plane_btn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Side_Plane_btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Side_Plane_btn_2MousePressed(evt);
            }
        });
        side_plane_btn1_con1.add(Side_Plane_btn_2);
        Side_Plane_btn_2.setBounds(20, 17, 250, 25);

        home_icon9.setForeground(new java.awt.Color(255, 255, 255));
        side_plane_btn1_con1.add(home_icon9);
        home_icon9.setBounds(20, 0, 30, 50);

        Sideplane1.add(side_plane_btn1_con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 50));
        Sideplane1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, 20));

        sidePlane_JAVA_label1.setBackground(new java.awt.Color(255, 255, 255));
        sidePlane_JAVA_label1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        sidePlane_JAVA_label1.setForeground(new java.awt.Color(255, 255, 255));
        sidePlane_JAVA_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sidePlane_JAVA_label1.setText("Covid-19");
        sidePlane_JAVA_label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sidePlane_JAVA_label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidePlane_JAVA_label1MousePressed(evt);
            }
        });
        Sideplane1.add(sidePlane_JAVA_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, 30));

        home_icon10.setForeground(new java.awt.Color(255, 255, 255));
        Sideplane1.add(home_icon10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(830, 680));

        jPanel2.setBackground(new java.awt.Color(102, 0, 238));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Beneficiary Cerificate");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel2.setText("Enter Mobile No");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Get OTP");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter OTP");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Enter Beneficiary ID");

        jButton3.setText("Download Certificate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Mobile Number Verifiction");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Certificate Download");

        dashboard_close_btn2.setBackground(new java.awt.Color(255, 255, 255));
        dashboard_close_btn2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        dashboard_close_btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard_close_btn2.setText("X");
        dashboard_close_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboard_close_btn2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboard_close_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(dashboard_close_btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel6)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addContainerGap(231, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sideplane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 746, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 300, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sideplane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Side_plane_btn_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_plane_btn_6MousePressed

    }//GEN-LAST:event_Side_plane_btn_6MousePressed

    private void side_plane_btn2_con1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_side_plane_btn2_con1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_side_plane_btn2_con1MouseClicked

    private void side_plane_btn2_con1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_side_plane_btn2_con1MousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_side_plane_btn2_con1MousePressed

    private void Side_plane_btn_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_plane_btn_9MousePressed
    }//GEN-LAST:event_Side_plane_btn_9MousePressed

    private void Side_Plane_btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Side_Plane_btn_2MousePressed
            
        new basic().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Side_Plane_btn_2MousePressed

    private void sidePlane_JAVA_label1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePlane_JAVA_label1MousePressed
       
    }//GEN-LAST:event_sidePlane_JAVA_label1MousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mobile = jTextField1.getText();

        String bodi = "{\r\n    \"mobile\": \""+mobile+"\"\r\n}";
        System.err.println(bodi);
        Unirest.setTimeouts(0, 0);
        HttpResponse<String> response;
        try {
            response = Unirest.post("https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP")
            .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36")
            .header("accept", "application/json")
            .header("Content-Type", "application/json")
            .body(bodi)
            .asString();
            Object obj = new JSONParser().parse(response.getBody());
            System.out.println(response.getStatus());
            System.out.println(response.getBody());

            //txnid
            JSONObject json = (JSONObject) obj;
            txn_id = (String) json.get("txnId");

        } catch (UnirestException | ParseException ex) {
            Logger.getLogger(Download_Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String otp = jTextField2.getText();
        String otphash;
        try {
            otphash = toHexString(getSHA(otp));
            Unirest.setTimeouts(0, 0);
            String bodi2 = "{\n    \"otp\": \""+otphash+"\",\n    \"txnId\": \""+txn_id+"\"\n}";
            System.err.println(bodi2);
            HttpResponse<String> response1 = Unirest.post("https://cdn-api.co-vin.in/api/v2/auth/public/confirmOTP")
            .header("accept", "application/json")
            .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36")

            .header("Content-Type", "application/json")
            .body(bodi2)
            .asString();
            System.out.println(response1.getStatus());
            System.out.println(response1.getBody());
            if (response1.getStatus()==200){
                JOptionPane.showMessageDialog(jButton2, "OTP Verified Enter your benficiary id to download you certificate");
                Object obj1;
                obj1 = new JSONParser().parse(response1.getBody());
                JSONObject json1 = (JSONObject) obj1;
                token = (String) json1.get("token");
            }
            else{
                JOptionPane.showMessageDialog(this, "Entered Wrong OTP Please try again");
            }

        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Download_Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }

        catch (ParseException ex) {
            Logger.getLogger(Download_Certificate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnirestException ex) {
            Logger.getLogger(Download_Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            Unirest.setTimeouts(0, 0);
            Scanner sc = new Scanner(System.in);
            System.out.print("Enter beneficiary id ");
            String s = jTextField3.getText();
            HttpResponse<String> response = Unirest.get("https://cdn-api.co-vin.in/api/v2/registration/certificate/public/download?beneficiary_reference_id="+s)
            .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36")

            .header("accept", "application/pdf")
            .header("Authorization", "Bearer "+token)

            .asString();
            System.out.println(response.getStatus());

            if(response.getStatus()==200){
                JOptionPane.showMessageDialog(this, "Certificate Download Sucessfully at Desktop");
            }
            InputStream is = response.getRawBody();
            BufferedInputStream fileParse = new BufferedInputStream(is);
            PDDocument document = null;
            document = PDDocument.load(fileParse);
            String st = System.getProperty("user.name");
            System.out.println(st);
            document.save("C:\\Users\\"+st+"\\Desktop\\certificate.pdf");
            new PDFTextStripper().getText(document);
            String pdfContent = new PDFTextStripper().getText(document);
            System.out.println(pdfContent);

        } catch (UnirestException | IOException ex) {
            Logger.getLogger(Download_Certificate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void dashboard_close_btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_close_btn2MousePressed
        System.exit(0);
    }//GEN-LAST:event_dashboard_close_btn2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Side_Plane_btn_2;
    private javax.swing.JLabel Side_plane_btn_6;
    private javax.swing.JLabel Side_plane_btn_9;
    private javax.swing.JPanel Sideplane1;
    private javax.swing.JLabel dashboard_close_btn2;
    private javax.swing.JLabel home_icon10;
    private javax.swing.JLabel home_icon8;
    private javax.swing.JLabel home_icon9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel sidePlane_JAVA_label1;
    private javax.swing.JPanel side_plane_btn1_con1;
    private javax.swing.JPanel side_plane_btn2_con1;
    private javax.swing.JPanel side_plane_btn5_con1;
    // End of variables declaration//GEN-END:variables
}
